version: "3.4"
networks:
 etl_net:

services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    networks:
      - etl_net
  
  adminer:
    image: adminer
    ports:
      - 9080:8080
    environment:
      ADMINER_DESIGN: 'nette'
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
      - etl_net